server:
  port: 8080
  servlet:
    session:
      timeout: 1800
      tracking-modes: COOKIE
  tomcat:
    uri-encoding: utf-8
#spring 환경 설정 그룹
#실제 운영 application-prod.yml은 프로젝트 외부에 보관 (보안)
spring:
  profiles:
    group:
      "prod" : "proddb,common"
      "dev" : "localdb,common"
    active: dev

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

#local 환경(개발)#
---
spring:
  config:
    activate:
      on-profile: "localdb"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jejulu
    username: root
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    hello:
      jejulu: debug

firebase:
  # 파이어베이스 엑세스 키 (외부 보관)
  config : /Users/app/config/firebase/firebaseAdminSdk.json
  bucket: jejulu-3b679.appspot.com

#공통 환경#
---
spring:
  config:
    activate:
      on-profile: "common"

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  messages:
    basename: errors

  thymeleaf:
    cache: true
    prefix: classpath:/templates/

---
## Test 환경
#
#spring:
#  config:
#    activate:
#      on-profile: test
#
#  h2:
#    console:
#      enabled: true
#
#  jpa :
#    database: h2
#    generate-ddl: on
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test_jejulu
#    username: sa
#    password:
#




